language : ruby

rvm:
  - 1.8
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
notifications:
    email:
        - vidyatest@hotmail.com
        - vidya@shippable.com
